Datastore FE
googleinterns/step263-2020 pull request #6
Opened 2020-09-24 07:44 UTC by NaamaHolzer

Connect the front end to the back end - use 'get' to fetch existing markers from the Datastore and 'post' to store new ones.

2020-09-24 08:15 UTC, NoyFlat requested changes

2020-09-24 08:15 UTC, NoyFlat commented on capstone-project/src/main/webapp/map/map.component.js
> +        function postMarker(marker) {
All other function are anonymous functions, and this one is a regular function definition.
I think it's better if we just choose one way to declare functions and stick to it.

2020-09-24 08:19 UTC, NoyFlat commented on capstone-project/src/main/webapp/map/map.component.js
> +        //Fetches markers from the backend and adds them to the map.
Missing a space after //

2020-09-24 08:27 UTC, orarch commented on capstone-project/src/main/webapp/map/map.component.js
> +        function postMarker(marker) {
There's inconsistency in this file on defining functions, e.g, buildInfoWindowInput is assigned to a variable. 

Let's be consistent if we can, I like it better the way you defined it here.

2020-09-24 08:27 UTC, orarch commented on capstone-project/src/main/webapp/map/map.component.js
> +        $http({
Why not use the $http.get method? 

https://docs.angularjs.org/api/ng/service/$http#get

2020-09-24 08:27 UTC, orarch commented on capstone-project/src/main/webapp/map/map.component.js
> +            $http({
Why not use the $http.post method? 
https://docs.angularjs.org/api/ng/service/$http#post

2020-09-24 10:35 UTC, NoyFlat approved these changes

2020-09-27 08:04 UTC, orarch approved these changes

2020-09-27 11:19 UTC, merged